# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

#######################################################################################
# Jekyll site settings
title: Digital Signals Theory
author: Brian McFee
email: brian.mcfee@nyu.edu
copyright:  "2020-2023"
logo: "content/images/logo/dstlogo.png"
exclude_patterns: [content/unused/*, content/setup.ipynb, content/chapter-covers.ipynb]
only_build_toc_files        : true

#######################################################################################
# Execution settings
execute:
  execute_notebooks         : 'cache' # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  timeout                   : -1
  #cache                     : ""  # A path to the jupyter cache that will be used to store execution artifacs. Defaults to `_build/.jupyter_cache/`
  #exclude_patterns          : []  # A list of patterns to *skip* in execution (e.g. a notebook that takes a really long time)

#######################################################################################
# Parse and render settings
parse:
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    # - html_admonition
    # - html_image
    - linkify
    # - replacements
    - smartquotes
    - substitution

  myst_url_schemes          : [mailto, http, https]  # URI schemes that will be recognised as external URLs in Markdown links


#######################################################################################
# HTML-specific settings
html:
  favicon                   : ""  # A path to a favicon image
  navbar_number_sections    : True  # Add a number to each section in your left navbar
  navbar_footer_text        : 'Powered by <a href="https://jupyterbook.org">Jupyter Book</a>'  # Will be displayed underneath the left navbar.
  google_analytics_id       : "UA-89057641-1"  # A GA id that can be used to track book views.
  home_page_in_navbar       : true  # Whether to include your home page in the left Navigation Bar
  use_edit_page_button      : false  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  baseurl                   : ""  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  use_multitoc_numbering    : true

#######################################################################################
# Launch button settings
launch_buttons:
  notebook_interface        : "jupyterlab"  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : ""  # "https://mybinder.org"  # The URL of the BinderHub (e.g., https://mybinder.org)
  jupyterhub_url            : ""  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
  thebe                  : false  # Add a thebelab button to pages (requires the repository to run on Binder)
  colab_url                 : "https://colab.research.google.com"

repository:
  url                       : "https://github.com/bmcfee/dstbook"  # The URL to your book's repository
  path_to_book              : ""  # A path to your book's folder, relative to the repository root.
  branch                    : main  # Which branch of the repository should be used when creating links

#######################################################################################
# Advanced and power-user settings
sphinx:
  extra_extensions:
      # - sphinx_jupyterbook_latex
      - sphinxcontrib.inkscapeconverter
      - sphinx_exercise
      - sphinx_proof
  config:
    # jblatex_load_imgconverter: true
    # jblatex_captions_to_parts: true
    html_theme_options:
      use_download_button: false
    mathjax3_config:
      loader:
        load:
          - "[tex]/configMacros"
          - "[tex]/html"
      tex:
        packages:
          "+": 
            - configMacros
            - html
        macros:
           "blue": ["\\class{blue}{#1}", 1]
           "red": ["\\class{red}{#1}", 1]
           "orange": ["\\class{orange}{#1}", 1]
           "purple": ["\\class{purple}{#1}", 1]
           "green": ["\\class{green}{#1}", 1]
           "dkorange": ["\\class{dkorange}{#1}", 1]
           "cyan": ["\\class{cyan}{#1}", 1]
           "magenta": ["\\class{magenta}{#1}", 1]
           "yellow": ["\\class{yellow}{#1}", 1]
           "peagreen": ["\\class{peagreen}{#1}", 1]
           "darkblue": ["\\class{darkblue}{#1}", 1]
           "darkorange": ["\\class{darkorange}{#1}", 1]

    latex_elements:
      geometry: "\\usepackage[papersize={7in, 10in}]{geometry}"
      extrapackages: "\\usepackage{cancel,color}\n\\usepackage{epigrafica}\n"
      preamble: \input{colormap.tex.txt}
      tableofcontents: ""
    latex_additional_files: ["colormap.tex.txt", "Alon.cls", "epigrafica.sty"]
    latex_docclass:
        howto: "Alon"
        manual: "Alon"
        latex_toplevel_sectioning: 'part'

latex:
  use_jupyterbook_latex: false
  latex_engine: xelatex
  latex_documents:
    targetname: dstbook.tex

bibtex_bibfiles:
    - content/references.bib

bibtex_reference_style: author_year  # or label, super, \supercite
